### ISSUE TITLE
very long install time

### ISSUE THREAD

**Issue by anandthakker** [developmentseed/project-seed#13]
On OS X, the initial `npm install` for this project takes a pretty seriously long time due to a number of things that get built from source on postinstall.  On my system, `browser-sync` is definitely the worst offender (and it's really browser-sync's dependency on the `ws` package that requires a slow build).

`watchify` and `gulp-imagemin` are a little slow too, but orders of magnitude faster.

I definitely think `browser-sync` has better functionality than the other similar options (`livereload`, etc.)... but is it better enough to be worth a 5+ minute initial install?  

IMO, a really important feature of a boilerplate project like this one is, in addition to providing consistency, it makes it really fast to boot up a brand new project and start hacking.

**Comment by jflasher** [comment]
Yeah, I can see the argument here, but I don't know that I see a good alternative. If we switched to something else, we'd be saying, 'We're continuously using something we know to be less useful because we didn't want to spend the extra 2 minutes on bootstrap a month ago.' That doesn't feel right either.

**Comment by anandthakker** [comment]
Yah, agreed. Hmm..... I wonder if it's possible to have a global install of
some of these modules... also not super ideal, I know, but until NPM starts
caching built packages it might be okay...?

**Comment by anandthakker** [comment]
Just gonna flag this again.  I have continued to have `npm install`s take an incredibly long time--over 10 minutes, and sometimes simply hanging and never finishing--specifically because of browsersync.  It's not a big deal when working on a single project for a long time, but if you're just trying to jump in and help on something, it creates a real roadblock.

**Comment by drewbo** [comment]
Will the gulp process default to the global module? Then we could maybe make two `npm install` options, only one of which brings in `browser-sync` and `ws` for internal use

**Comment by anandthakker** [comment]
Another approach would be to make this whole thing into a yeoman generator that offered a menu of build features to choose from.  (So that, for instance, one could simply opt out of the browsersync part)

**Comment by jflasher** [comment]
I like the idea of a yeoman generator (would help us settle our compass question as well) but I don't have a good sense of how hard it'd be to maintain?

**Comment by anandthakker** [comment]
@jflasher - yeah, neither do i... probably proportional to how deeply
configurable we make it, but i'm not sure.
