### ISSUE TITLE
Figure out how to utilize env/build variables

### ISSUE THREAD

**Issue by jflasher** [developmentseed/project-seed#14]
For example, we have a site that deploys to staging and production and needs to grab data from a data url and it should point to the staging or production data url where appropriate. I had thought to use something like https://github.com/developmentseed/developmentseed.github.com/blob/publish/gulpfile.js#L254 and then hook up [gulp-replace](https://github.com/lazd/gulp-replace) to do a string replace. It works for a build, but looks a little ugly and things start to get worse when considering how to hook this up with `serve` (versus `build`). I may have been overcomplicating it a bit since this shouldn't be too hard?

**Comment by anandthakker** [comment]
@jflasher for controlling js front end code configuration, I'm using 'envify'. It's a browserify transform that replaces `process.env.BLAH` in your code with the environment variable BLAH (from the shell environment where the build is run).   

And to keep all such environment references in one place I've put em in a `config.js` file that the app can `require`, like so: https://github.com/developmentseed/india-lights/blob/develop/app/scripts/config.js

**Comment by scisco** [comment]
I use something called `envloader`. It loads variables from `.env` file. This approach works well with Heroku env variables. You can use .env in development and heroku env variables in production.

**Comment by jflasher** [comment]
@scisco I like envloader on the projects we've used it on, but not sure it'd work well for frontend code? 

@anandthakker what do you think would be the best way to roll out that config.js keeping in mind that'd we'd need different vars for dev, staging, production, etc. Maybe do three different objects within the main object?

**Comment by anandthakker** [comment]
@jflasher Very possible that I'm missing something important, but I was imagining something like this:

`config.js`:
```javascript
module.exports = {
  dbUrl: process.env.DATABASE_URL || 'Default Value For Use In Development',
  oauthSecretDoohickey: process.env.OAUTH_DOOHICKEY || 'local_throwaway_token'
}
```

Then just set the appropriate environment vars on staging and production servers, and Bob's your uncle!

**Comment by anandthakker** [comment]
Whoops -- "on staging and production servers" should really read: "on travis when running the staging or production build scripts"

**Comment by jflasher** [comment]
@anandthakker and I talked this over a bit more and we think we have a good way forward. You should all be very excited.

**Comment by anandthakker** [comment]
@jflasher Trying to remember what we decided here.  I think we were going to have the app read from `config.js`.  We'd also have a `config.production.js` and a `config.staging.js`.  The build scripts would copy the appropriate one (depending on `TRAVIS_BRANCH`) to `config.js`.

I also think we said that the gulpfile would automatically copy over the staging one whenever `config.js` was missing.

**Comment by jflasher** [comment]
I think that's right. I really should've been more clear in my comment right after we talked about it.
