### ISSUE TITLE
Console.log logo broken on FF

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/project-seed#23]
<img width="555" alt="screen shot 2015-07-13 at 8 13 03 am" src="https://cloud.githubusercontent.com/assets/1590802/8649278/d3d3f5d0-2936-11e5-9367-0b1ea0204743.png">

On firefox 38

**Comment by anandthakker** [comment]
bummer.

**Comment by dereklieu** [comment]
It's kind of post-modern though. Really jumps out of the frame.

**Comment by danielfdsilva** [comment]
This is now working, both with firebug and firefox native devtools
