### ISSUE TITLE
Break the build on lint errors?

### ISSUE THREAD

**Issue by jflasher** [developmentseed/project-seed#31]
@anandthakker mentioned this in https://github.com/developmentseed/project-seed/issues/30 and while I was previously against it, having done it on a few projects now, I think I'm more into it. My worries about not being able to deploy are outweighed by my love of cleanly linted files.

As for tooling, we're using semistandard and I know it has tooling for ST and Atom and I imagine vim will work with anything via the command line?

**Comment by anandthakker** [comment]
> I imagine vim will work with anything via the command line?

Yep, pretty much -- I recommend using [Syntastic](https://github.com/scrooloose/syntastic)

**Comment by jflasher** [comment]
Closing this as we've generally implemented breaking on staging and non-breaking on production.
