### ISSUE TITLE
Include babelify by default

### ISSUE THREAD

**Issue by anandthakker** [developmentseed/project-seed#33]
If we included the `babelify` transform here, then we could start to just write ES6 by default and not worry about it.  Babelify is a browserify transform that uses [babel](babeljs.io) to transpile es6 to es5.

**Comment by jflasher** [comment]
:+1:

**Comment by drewbo** [comment]
Seriously :heart_eyes: 

And sorry to anyone has to review my code in the future because at least once I'm going to test out some unicode support

`let ⅅ = '螖'`

**Comment by dereklieu** [comment]
+1 onboard with this.

**Comment by jflasher** [comment]
Closed by https://github.com/developmentseed/project-seed/pull/35
