### ISSUE TITLE
uglify doesn't like React

### ISSUE THREAD

**Issue by jflasher** [developmentseed/project-seed#34]
Putting here to remind me to look into this more. Pretty sure https://github.com/developmentseed/project-seed/blob/master/gulpfile.js#L189 was barfing on some JSX during build (not serve).

**Comment by anandthakker** [comment]
@jflasher Hmm, shouldn't the JSX have been transformed already at that point?

**Comment by jflasher** [comment]
The `javascript` task should be done before that happens so yeah, I'd think so. It could be failing on something else though, haven't dug too deep. Failing example is at https://github.com/openaq/openaq.github.io/tree/develop if anyone wants to run.

**Comment by jflasher** [comment]
Closing due to user error.
