### ISSUE TITLE
Proposal: use Yarn instead of NPM

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/project-seed#64]
[Yarn](https://yarnpkg.com/en/) is a replacement for NPM.

We should start using yarn instead of NPM as the default in project-seed.

When dependencies go out of date, it can take a whole day to debug what would otherwise be a simple fix. Yarn addresses this by locking dependency versions on default (NPM does this but it's a separate command that not everyone will remember to do).

As we age as a company and have a longer-running history of projects, this will become a bigger issue, especially if we continue to use cutting-edge tools that go through a lot of breaking changes.

@kamicut and @drewbo have been using yarn for a few projects now. Maybe one of you could post on how the workflow is different?

**Comment by drewbo** [comment]
Discussed in our dev meeting today and seems like everyone is on board cc: @mileswwatkins @danielfdsilva @matthewhanson @DylanMoriarty @sethvincent. Help migrating:

https://yarnpkg.com/lang/en/docs/migrating-from-npm/

I'll own creating a PR to update the docs, dependencies, lock file, and travis instructions
