### ISSUE TITLE
Use uglify-es

### ISSUE THREAD

**Issue by danielfdsilva** [developmentseed/project-seed#76]
![image](https://user-images.githubusercontent.com/1090606/53562844-5f0fcb00-3b4a-11e9-940c-d1e7bd093571.png)

>  Project seed it’s using uglify-js which does not support es6 syntax, and many browser-based libraries are now shipping es6 syntax as it’s being supported natively in more and more browsers.

**Comment by Rub21** [comment]
from @dereklieu 's recommendation: 
- https://github.com/developmentseed/nethope-sitrep-frontend/blob/develop/gulpfile.js#L209
- https://github.com/developmentseed/nethope-sitrep-frontend/blob/develop/gulpfile.js#L21


 I have updated the  the data-seed: https://github.com/developmentseed/data-seed/commit/fb18dcc789ca383ba6b3886790eb6636ee54ba3a
but it takes to much time for compile and throwing an error: 
![image](https://user-images.githubusercontent.com/1152236/53667606-7da3be00-3c3f-11e9-8caf-bf355205236a.png)

**Comment by Rub21** [comment]
I've fixed it adding the  flag `--max_old_space_size=5048` https://github.com/developmentseed/data-seed/commit/be6dc889535af397722d4af32da4b8d36040afd7
