### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/project-seed#89]
We need to clarify if project-seed supports tree shaking, and if not, enabled it to remove code that is not used in production builds.

Another benefit is to allow loading "micro" modules (`lodash.get`, `@turf/area`) more easily by installing the full library and using `import` statements.

**Comment by danielfdsilva** [comment]
Project seed v4 did not support tree shaking.
Current version, using Parcel, will tree shake libraries if they're build as such
