### ISSUE TITLE
Let's talk about line length

### ISSUE THREAD

**Issue by anandthakker** [developmentseed/project-seed#9]
80 characters.  Reason?  Read this:

```javascript
if (lineLength > 80) { return [ 'You', 'must', 'hate', 'me', 'and', 'not', 'want', 'me', 'to', 'be', 'happy', ':-('].map(function (x) { return x.toUpperCase(); }).join(' '); }
```

See how annoying that was?  Whereas

```


























































```

you got down here no problem!

**Comment by scisco** [comment]
@anandthakker I use 119, which is apparently the width of github code-view page.

**Comment by jflasher** [comment]
I rock 80.

**Comment by drewbo** [comment]
I'm a fan of 119; 80 makes it hard to write [documentation for functions](https://github.com/documentationjs/documentation/blob/master/GETTTING_STARTED.md#the-essentials)

**Comment by anandthakker** [comment]
My reason for 80 is that it enables two side-by-side code windows on most editors and, similarly, makes it much easier to read side-by-side diffs.

@drewbo Why does 80 make it harder to write function docs?  It seems to me like there's no avoiding running into the width limit, whether it's 80 or 119, so in either case, it's worth using a text editor feature for comment-aware auto line wrapping...

**Comment by scisco** [comment]
@anandthakker it makes it easier to read on side-by-side view, but I think sometimes it actually makes it harder to read in a single view because you have to break lines of codes that are easier to read and understand in one line.

I suggest not to institute a company-wide rule as clearly there are multiple opinions on this issue.

**Comment by anandthakker** [comment]
@scisco I know what you mean about how breaking lines can make things harder to understand.  Often, such lines are doing a lot at once, and can be very readably broken
into multiple statements... but that's definitely not always true, so I do see your point.

I also very much agree that we shouldn't force a company-wide rule on this (or on most things, really)... but that doesn't mean I won't campaign obnoxiously for 80 all day long :)
